### ISSUE TITLE
Can't disassemble for architecture UNKNOWN!

### ISSUE THREAD

**Issue by legoboy0215** [PEMapModder/DecMcpe#1]
How do I fix this issue?

**Comment by PEMapModder** [comment]
I used objdump from Android NDK distributions

This isn't a problem of DecMcpe anyway.

**Comment by legoboy0215** [comment]
_Noo..._

**Comment by PEMapModder** [comment]
Download the NDK for your OS from [Android website](http://developer.android.com/ndk/downloads/index.html).

**Comment by Creeperface01** [comment]
i installed NDK but still doesn't work

**Comment by PEMapModder** [comment]
Your own problem. Issues are not help threads.
